name: dsp_isaque
description: Um simples aplicativo de linha de comando que criei para estudar algoritmos de processamento de imagem simples em dart
version: 1.0.0
homepage: https://www.example.com
author: isaque neves <insinfo2008@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
#  path: ^1.6.0
  image: ^2.1.12

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
